# Generated by Django 4.2.7 on 2023-12-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_remove_review_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
