# Generated by Django 4.2.7 on 2023-12-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_review_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='complete',
        ),
    ]
